# Generated by Django 3.1.3 on 2020-11-28 16:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gruporouters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=12, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('site', models.CharField(choices=[(None, 'Estados do Brasil'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RR', 'Roraima'), ('RO', 'Rondônia'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Site')),
                ('device_type', models.CharField(choices=[('JU', 'Juniper'), ('CI', 'Cisco'), ('EX', 'Extreme'), ('HU', 'Huawei')], max_length=2, verbose_name='Device Type')),
                ('ipaddress', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address], verbose_name='IP address')),
                ('sshport', models.CharField(max_length=4, verbose_name='SSH port')),
                ('gruporouter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruporouters.gruporouter')),
            ],
        ),
    ]
